version: "3"

services:

  mysql-server:
    image: mysql:5.7.4
    container_name: mysql5.7
    command:
      - --default_authentication_plugin=mysql_native_password
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    ports:
    - 6607:3306
    volumes:
      - /Users/boyizhang/opt/data/mysql:/var/lib/mysql
      - /Users/boyizhang/opt/data/conf/mysql/mysqld.cnf:/etc/mysql/mysql.conf.d/mysqld.cnf
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: sosotest_data
      MYSQL_USER: root
      MYSQL_PASSWORD: 123456

  redis-server:
    image: redis:4.0.2
    container_name: myredis
    volumes:
      - /Users/boyizhang/opt/data/redis:/data
    ports:
    - 6380:6379
  sosotest-server:
    build:
      context: .
      dockerfile: sosotest.dockerfile
    container_name: sosotest_server
    depends_on:
#      - mysql-server
      - redis-server
    ports:
      - "1211:1211"
    restart: always



#  sosotest-service:
#    image: sosotest.01:latest
#    command: python3 AutotestWebD/manage.py runserver 0.0.0.0:1211
#    ports:
#      - "1211:1211"
#    restart: always
#  sosotest-master:
#    image: sosotest.01:latest
#    depends_on:
#      - sosotest-service
#    command: python3 AutotestFramework/test_run/main.py
#    restart: always
#    ports:
#      - "9298:9298"
#  sosotest-slave:
#    image: sosotest.01:latest
#    depends_on:
#      - sosotest-master
#    command: python3 AutotestFramework/test_run/run.py  --ip 192.168.0.100
#    restart: always